// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fmqzuyjhwxcltuilxhpq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZtcXp1eWpod3hjbHR1aWx4aHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYxMTM3MDYsImV4cCI6MjA2MTY4OTcwNn0.jRDw_FBpoXJD3Y7AK2CVKgOCHhjCVEij0G4NByqQvpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);